# Generated by Django 4.0 on 2022-01-04 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_toy_alter_feeding_options_alter_feeding_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiger',
            name='toys',
            field=models.ManyToManyField(to='main_app.Toy'),
        ),
    ]
